# Generated by Django 5.1.4 on 2025-01-21 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pokemons', models.ManyToManyField(related_name='teams', to='pokemon.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainer1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_trainer1', to='pokemon.team')),
                ('trainer2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_trainer2', to='pokemon.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles_won', to='pokemon.team')),
            ],
        ),
    ]
